create table
  public.cart_contents (
    cart_id integer not null,
    potion_id integer not null,
    quantity integer not null,
    constraint cart_contents_pk primary key (cart_id, potion_id),
    constraint cart_contents_cart_id_fk foreign key (cart_id) references carts (cart_id),
    constraint cart_contents_potion_id_fk foreign key (potion_id) references potions (potion_id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer_name text not null,
    constraint carts_pkey primary key (cart_id)
  ) tablespace pg_default;

create table
  public.fluids (
    fluid_id bigint generated by default as identity,
    color text not null,
    quantity bigint not null default '0'::bigint,
    fluid_type integer[] not null,
    constraint fluids_pkey primary key (fluid_id)
  ) tablespace pg_default;

create table
  public.global_inventory (
    gold integer not null,
    id integer generated by default as identity,
    constraint global_inventory_pkey primary key (id),
    constraint global_inventory_id_key unique (id)
  ) tablespace pg_default;

create table
  public.potions (
    potion_id bigint generated by default as identity,
    sku text not null,
    potion_type integer[] not null,
    price bigint not null,
    quantity bigint not null default '0'::bigint,
    constraint potions_pkey primary key (potion_id),
    constraint potions_sku_key unique (sku)
  ) tablespace pg_default;